### ISSUE TITLE
Building Unreal Plugin Fails

### ISSUE THREAD

**Issue by sp-ent** [mixer/interactive-unreal-plugin#37]
When I try to build the plugin from the command line it fails with the following error. I'm attempting the build with a pre-build version of the engine. UE 4.16.3, Win 10, VS 2017

At the command line:
Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): C:\Program Files\Epic Games\UE_4.16\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4Editor Win64 Development -project="C:\Users\chris.SP-ENT\Downloads\Mixer\interactive-unreal-plugin-master\UnrealPlugin\HostProject\HostProject.uproject"  -module MixerInteractivity -module MixerInteractivityEditor -module MixerInteractivityBlueprintNodes -receipt C:\Users\chris.SP-ENT\Downloads\Mixer\interactive-unreal-plugin-master\UnrealPlugin\HostProject\Plugins\Mixer\Binaries\Win64\UE4Editor.target -NoHotReload. See logfile for details: 'UnrealBuildTool-2018.04.21-20.11.48.txt'
   at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback) in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\ProcessUtils.cs:line 913
   at AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback) in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\ProcessUtils.cs:line 866
   at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars) in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\UBTUtils.cs:line 51
   at BuildPlugin.CompilePluginWithUBT(FileReference HostProjectFile, FileReference HostProjectPluginFile, PluginDescriptor Plugin, String TargetName, TargetType TargetType, UnrealTargetPlatform Platform, UnrealTargetConfiguration Configuration, List`1 ReceiptFileNames, String InAdditionalArgs) in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\Scripts\BuildPluginCommand.Automation.cs:line 192
   at BuildPlugin.CompilePlugin(FileReference HostProjectFile, FileReference HostProjectPluginFile, PluginDescriptor Plugin, List`1 HostPlatforms, List`1 TargetPlatforms, String AdditionalArgs) in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\Scripts\BuildPluginCommand.Automation.cs:line 134
   at BuildPlugin.ExecuteBuild() in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\Scripts\BuildPluginCommand.Automation.cs:line 91
   at AutomationTool.BuildCommand.Execute() in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 100
   at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands) in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 566
   at AutomationTool.Automation.Process(String[] Arguments) in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 536
   at AutomationTool.Program.MainProc(Object Param) in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\Program.cs:line 133
   at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param) in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\Utils.cs:line 708
   at AutomationTool.Program.Main() in C:\Program Files\Epic Games\UE_4.16\Engine\Source\Programs\AutomationTool\Program.cs:line 57

Unreal Build Tool Log:
Creating makefile for UE4Editor (no existing makefile)
Performing full C++ include scan (no include cache file)
Parsing headers for UE4Editor
  Running UnrealHeaderTool "C:\Users\chris.SP-ENT\Downloads\Mixer\interactive-unreal-plugin-master\UnrealPlugin\HostProject\HostProject.uproject" "C:\Users\chris.SP-ENT\Downloads\Mixer\interactive-unreal-plugin-master\UnrealPlugin\HostProject\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
C:/Users/chris.SP-ENT/Downloads/Mixer/interactive-unreal-plugin-master/UnrealPlugin/HostProject/Plugins/Mixer/Source/MixerInteractivity/Public/MixerInteractivityProjectAsset.h(17) : Error: Unrecognized type 'FSoftClassPath' - type must be a UCLASS, USTRUCT or UENUM
Error: UnrealHeaderTool failed for target 'UE4Editor' (platform: Win64, module info: C:\Users\chris.SP-ENT\Downloads\Mixer\interactive-unreal-plugin-master\UnrealPlugin\HostProject\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest, exit code: OtherCompilationError (5)).

**Comment by jsyarrow** [comment]
The latest source ought to be compatible with either 4.18 or 4.19.  For 4.16 you'll need an older version of the plugin.  [This release](https://github.com/mixer/interactive-unreal-plugin/releases/tag/v0.9.1-beta) ought to work.

**Comment by sp-ent** [comment]
Thanks James, I'll give that a try. Just wondering, does that version have mobile support?

**Comment by sp-ent** [comment]
Another update on this issue. Working in both UE 4.17 and 4.18 we get the following errors while trying to build the mixer plugin.

The following shows in the command window.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
1755,5): warning : The referenced project '..\IOS\MobileDeviceInterface\MobileDeviceInterface.csproj' does not exist. [
C:\Program Files\Epic Games\UE_4.18\Engine\Source\Programs\AutomationTool\AutomationTool.csproj]

The following is the error in the Automation Tool log file.
==============================================================================
ExceptionUtils.PrintExceptionInfo: ERROR: Missing -Package=... argument
ExceptionUtils.PrintExceptionInfo:        (see C:\Program Files\Epic Games\UE_4.18\Engine\Programs\AutomationTool\Saved\Logs\UAT_Log.txt for full exception trace)
ExceptionUtils.PrintExceptionInfo: 
ExceptionUtils.PrintExceptionInfo: AutomationException: Missing -Package=... argument
ExceptionUtils.PrintExceptionInfo:    at BuildPlugin.ExecuteBuild() in C:\Program Files\Epic Games\UE_4.18\Engine\Source\Programs\AutomationTool\Scripts\BuildPluginCommand.Automation.cs:line 44
ExceptionUtils.PrintExceptionInfo:    at AutomationTool.BuildCommand.Execute() in C:\Program Files\Epic Games\UE_4.18\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 100
ExceptionUtils.PrintExceptionInfo:    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, Dictionary`2 Commands) in C:\Program Files\Epic Games\UE_4.18\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 558
ExceptionUtils.PrintExceptionInfo:    at AutomationTool.Automation.Process(String[] Arguments) in C:\Program Files\Epic Games\UE_4.18\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 528
ExceptionUtils.PrintExceptionInfo:    at AutomationTool.Program.MainProc(Object Param) in C:\Program Files\Epic Games\UE_4.18\Engine\Source\Programs\AutomationTool\Program.cs:line 132
ExceptionUtils.PrintExceptionInfo:    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param) in C:\Program Files\Epic Games\UE_4.18\Engine\Source\Programs\AutomationTool\AutomationUtils\Utils.cs:line 708
ExceptionUtils.PrintExceptionInfo:    at AutomationTool.Program.Main() in C:\Program Files\Epic Games\UE_4.18\Engine\Source\Programs\AutomationTool\Program.cs:line 62
ExceptionUtils.PrintExceptionInfo: ==============================================================================
Program.Main: AutomationTool exiting with ExitCode=1 (Error_Unknown)

Not sure what's happening here but this may be a larger issue. We have yet to try it in 4.19 but will be doing so in the next day or so. I'll report what we find out. We don't need the plugin working on either 4.18 or 4.19 as we're upgrading our projects to 4.19. We will need it to work in 4.19 however.

Thanks James.

**Comment by jsyarrow** [comment]
Are you following the instructions [here](https://github.com/mixer/interactive-unreal-plugin/wiki/Working-with-a-pre-built-version-of-Unreal-Engine)?  The log suggests that you're missing the -package command line parameter, which is really just the output path for the built plugin.

I think the command window warning about MobileDeviceInterface is a red herring.

**Comment by sp-ent** [comment]
Well, that fixed the previous error, I was missing an = in the command line parameter. DOH! Thanks. We're now getting a different error.

Following is the log file with the error.

-------------------------------------------------------------------------------
--------------------Project: Default-------------------------------------------
PCH.UELinkerFixups.cpp (0:00.21 at +0:00)
UELinkerFixups.cpp (0:00.32 at +0:00)
InteractiveCppV2Sdk.cpp (0:03.78 at +0:00)
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\sal.h(2361): error C2144: syntax error: 'int' should be preceded by ';'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\sal.h(2361): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\chris.sp-ent\downloads\mixer\mixer plugin 4-17-2018\hostproject\plugins\mixer\thirdparty\include\interactive-cpp-v2\internal\common.h(15): warning C4668: '_DURANGO' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
c:\users\chris.sp-ent\downloads\mixer\mixer plugin 4-17-2018\hostproject\plugins\mixer\thirdparty\include\interactive-cpp-v2\internal/http_client.cpp(3): warning C4668: '_DURANGO' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
c:\users\chris.sp-ent\downloads\mixer\mixer plugin 4-17-2018\hostproject\plugins\mixer\thirdparty\include\interactive-cpp-v2\internal/http_client.cpp(13): warning C4668: '_DURANGO' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Users\chris.SP-ENT\Downloads\Mixer\Mixer Plugin 4-17-2018\HostProject\Plugins\Mixer\ThirdParty\Include\interactive-cpp-v2/interactivity.cpp(10): warning C4668: '_DURANGO' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Program Files (x86)\Windows Kits\8.1\include\um\winnt.h(17005): warning C4668: '_APISET_RTLSUPPORT_VER' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Program Files (x86)\Windows Kits\8.1\include\um\interlockedapi.h(73): warning C4668: '_APISET_INTERLOCKED_VER' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Program Files (x86)\Windows Kits\8.1\include\um\processthreadsapi.h(1170): warning C4668: '_WIN32_WINNT_WINTHRESHOLD' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Program Files (x86)\Windows Kits\8.1\include\um\securitybaseapi.h(357): warning C4668: '_APISET_SECURITYBASE_VER' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Program Files (x86)\Windows Kits\8.1\include\um\securitybaseapi.h(472): warning C4668: '_APISET_SECURITYBASE_VER' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Program Files (x86)\Windows Kits\8.1\include\um\securitybaseapi.h(1302): warning C4668: '_APISET_SECURITYBASE_VER' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(8618): warning C4668: 'NTDDI_WIN7SP1' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Windows\PostWindowsApi.h(35): warning C4668: 'PLATFORM_XBOXONE' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Users\chris.SP-ENT\Downloads\Mixer\Mixer Plugin 4-17-2018\HostProject\Plugins\Mixer\Source\MixerInteractivity\Private\InteractiveCppV2Sdk.cpp(28): error C2144: syntax error: 'int' should be preceded by ';'
C:\Users\chris.SP-ENT\Downloads\Mixer\Mixer Plugin 4-17-2018\HostProject\Plugins\Mixer\Source\MixerInteractivity\Private\InteractiveCppV2Sdk.cpp(28): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

Error executing C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe (tool returned code: 2)
MixerLoginPane.gen.cpp (0:03.98 at +0:04)
MixerInteractivityUserSettings.gen.cpp (0:03.39 at +0:08)
MixerInteractivitySettings.gen.cpp (0:03.07 at +0:11)
MixerInteractivityProjectAsset.gen.cpp (0:04.45 at +0:14)
MixerInteractivityCustomMethods.gen.cpp (0:03.45 at +0:19)
MixerInteractivityBlueprintLibrary.gen.cpp (0:03.70 at +0:22)
MixerInteractivity.init.gen.cpp (0:03.45 at +0:26)
MixerDynamicDelegateBinding.gen.cpp (0:04.67 at +0:29)
MixerCustomControl.gen.cpp (0:03.26 at +0:34)
SMixerLoginPane.cpp (0:05.93 at +0:37)
OnlineChatMixer.cpp (0:03.84 at +0:43)
MixerLoginPane.cpp (0:09.31 at +0:47)
MixerJsonHelpers.cpp (0:02.20 at +0:56)
MixerInteractivityModulePrivate.cpp (0:15.67 at +0:59)
MixerInteractivitySettings.cpp (0:03.43 at +1:14)
MixerInteractivityProjectAsset.cpp (0:03.50 at +1:18)
MixerInteractivityModule_WithSessionState.cpp (0:05.34 at +1:21)
MixerInteractivityModule_UE.cpp (0:04.26 at +1:27)
MixerInteractivityModule_Null.cpp (0:04.04 at +1:31)
MixerInteractivityModule_InteractiveCpp2.cpp (0:07.06 at +1:35)
MixerInteractivityModule_InteractiveCpp.cpp (0:04.42 at +1:42)
MixerInteractivityTypes.cpp (0:01.96 at +1:46)
MixerInteractivityJsonTypes.cpp (0:04.71 at +1:48)
MixerInteractivityBlueprintLibrary.cpp (0:08.87 at +1:53)
MixerDynamicDelegateBinding.cpp (0:11.70 at +2:02)
MixerCustomControl.cpp (0:09.79 at +2:14)
MixerChatConnection.cpp (0:07.00 at +2:23)
MixerBindingUtils.cpp (0:03.11 at +2:30)
C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Windows/WindowsPlatformCompilerSetup.h(186): warning C4668: 'UE_BUILD_DEBUG' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\HAL/Platform.h(852): warning C4668: 'UE_BUILD_DOCS' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
PCLaunch.rc (0:00.15 at +2:34)
---------------------- Done ----------------------
 
    Rebuild All: 0 succeeded, 1 failed, 0 skipped
 

ERROR: UBT ERROR: Failed to produce item: C:\Users\chris.SP-ENT\Downloads\Mixer\Mixer Plugin 4-17-2018\HostProject\Plugins\Mixer\Binaries\Win64\UE4-MixerInteractivity.lib
Total build time: 172.42 seconds (XGE executor: 0.00 seconds)

This is different than what was happening before. It generated something called HostProject which contains a sub folder called plugins which seems to contain the Mixer plugin, but we're not sure if it's complete or if there is something missing. Let me know what other information you may need and I'll be happy to provide it. This is a build against 4.19.2.

**Comment by sp-ent** [comment]
Thanks James. I'll download the new package and we'll do another build. I'll let you know what we encounter, hopefully later today.

**Comment by sp-ent** [comment]
Thanks James, for letting me know about the new commits. The fixes worked and we now have a working plugin in 4.19.2. I appreciate the updates and all the help.

**Comment by sp-ent** [comment]
I think we can mark this as solved.
